package com.careerosai.entity;

import com.careerosai.audit.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.validator.constraints.URL;

import java.util.UUID;

/**
 * Domain Entity representing Company Representative Profile Details.
 * Linked 1-to-1 with User entity.
 *
 * Design Decision - Fetch Strategy:
 * User relationship uses FetchType.LAZY to optimize database queries.
 */
@Entity
@Table(
    name = "company_profiles",
    indexes = {
        @Index(name = "idx_company_profiles_name", columnList = "company_name", unique = true)
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = false, of = "id")
public class CompanyProfile extends BaseEntity {

    /**
     * Primary Key UUID. Automatically generated by Hibernate UUID strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * User account owner associated with this Company Profile (1-to-1).
     * FetchType.LAZY avoids unnecessary join queries.
     */
    @NotNull(message = "Associated user account cannot be null")
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "id", nullable = false, unique = true)
    private User user;

    /**
     * Unique Registered Corporate Company Name.
     */
    @NotBlank(message = "Company name cannot be blank")
    @Column(name = "company_name", nullable = false, unique = true)
    private String companyName;

    /**
     * Official Corporate Website URL.
     */
    @URL(message = "Website must be a valid URL format (e.g. https://company.com)")
    @Column(name = "website")
    private String website;

    /**
     * Primary Headquarters or Office Location.
     */
    @Column(name = "location")
    private String location;

    /**
     * Business Domain / Industry Category.
     */
    @Column(name = "industry", length = 150)
    private String industry;

    /**
     * Detailed Overview & Mission Description of the Company.
     */
    @Size(max = 5000, message = "Description cannot exceed 5000 characters")
    @Column(name = "description", columnDefinition = "TEXT")
    private String description;
}
