package com.careerosai.entity;

import com.careerosai.audit.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * Domain Entity representing Student Profile Details.
 * Linked 1-to-1 with User entity.
 *
 * Design Decision - Fetch Strategy:
 * User relationship uses FetchType.LAZY to prevent eager query overhead when fetching profile details alone.
 */
@Entity
@Table(name = "student_profiles")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = false, of = "id")
public class StudentProfile extends BaseEntity {

    /**
     * Primary Key UUID. Automatically generated by Hibernate UUID strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * User account owner associated with this Student Profile (1-to-1).
     * FetchType.LAZY avoids unnecessary join queries.
     */
    @NotNull(message = "Associated user account cannot be null")
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", referencedColumnName = "id", nullable = false, unique = true)
    private User user;

    /**
     * Student Legal First Name.
     */
    @NotBlank(message = "First name cannot be blank")
    @Column(name = "first_name", nullable = false, length = 100)
    private String firstName;

    /**
     * Student Legal Last Name.
     */
    @NotBlank(message = "Last name cannot be blank")
    @Column(name = "last_name", nullable = false, length = 100)
    private String lastName;

    /**
     * Optional Contact Phone Number formatted in E.164 international standard.
     */
    @Pattern(regexp = "^\\+?[1-9]\\d{1,14}$", message = "Phone number must follow valid international E.164 format (e.g. +1234567890)")
    @Column(name = "phone", length = 20)
    private String phone;

    /**
     * Optional Profile Photo URL or Base64 string.
     */
    @Column(name = "profile_photo", columnDefinition = "TEXT")
    private String profilePhoto;

    /**
     * Gender string.
     */
    @Column(name = "gender", length = 20)
    private String gender;

    /**
     * Date of birth formatted as YYYY-MM-DD.
     */
    @Column(name = "date_of_birth", length = 20)
    private String dateOfBirth;

    /**
     * City location.
     */
    @Column(name = "city", length = 100)
    private String city;

    /**
     * State location.
     */
    @Column(name = "state", length = 100)
    private String state;

    /**
     * Country location.
     */
    @Column(name = "country", length = 100)
    private String country;

    /**
     * Academic Institution / University Name.
     */
    @NotBlank(message = "University name cannot be blank")
    @Column(name = "university_name", nullable = false)
    private String universityName;

    /**
     * Academic Degree (e.g. B.Tech, B.S., M.S., M.Tech).
     */
    @Column(name = "degree", length = 100)
    private String degree;

    /**
     * Major / Field of Study.
     */
    @NotBlank(message = "Major cannot be blank")
    @Column(name = "major", nullable = false, length = 150)
    private String major;

    /**
     * Branch / Department.
     */
    @Column(name = "branch", length = 150)
    private String branch;

    /**
     * Cumulative Grade Point Average (GPA) on a standard scale.
     */
    @DecimalMin(value = "0.0", message = "GPA cannot be negative")
    @DecimalMax(value = "10.0", message = "GPA cannot exceed 10.0")
    @Column(name = "gpa", precision = 3, scale = 2)
    private BigDecimal gpa;

    /**
     * Expected Graduation Year.
     */
    @NotNull(message = "Graduation year cannot be null")
    @Min(value = 2024, message = "Graduation year must be 2024 or later")
    @Max(value = 2035, message = "Graduation year cannot exceed 2035")
    @Column(name = "graduation_year", nullable = false)
    private Integer graduationYear;

    /**
     * Current Academic Semester (1 to 10).
     */
    @Min(value = 1, message = "Semester must be at least 1")
    @Max(value = 12, message = "Semester cannot exceed 12")
    @Column(name = "current_semester")
    private Integer currentSemester;

    /**
     * Personal About / Professional Bio summary.
     */
    @Column(name = "about", columnDefinition = "TEXT")
    private String about;

    /**
     * LinkedIn Profile URL.
     */
    @Column(name = "linkedin", length = 255)
    private String linkedin;

    /**
     * GitHub Profile URL.
     */
    @Column(name = "github", length = 255)
    private String github;

    /**
     * Portfolio / Personal Website URL.
     */
    @Column(name = "portfolio", length = 255)
    private String portfolio;
}
