package com.careerosai.entity;

import com.careerosai.audit.BaseEntity;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * Core Domain Entity representing System Users.
 * Inherits audit timestamps (createdAt, updatedAt) from BaseEntity.
 *
 * Design Decision - Fetch Strategy:
 * Roles relationship uses FetchType.EAGER because Spring Security requires
 * immediate access to granted authorities during token authentication without
 * triggering LazyInitializationException outside transactional boundaries.
 *
 * Design Decision - Cascade Strategy:
 * PERSIST and MERGE cascades are enabled to allow role association during user creation.
 * REMOVE cascade is strictly avoided to prevent accidental deletion of system roles.
 */
@Entity
@Table(
    name = "users",
    indexes = {
        @Index(name = "idx_users_email", columnList = "email", unique = true),
        @Index(name = "idx_users_deleted_at", columnList = "deleted_at")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = false, of = "id")
public class User extends BaseEntity {

    /**
     * Primary Key UUID. Automatically generated by Hibernate UUID strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Full Name of the User.
     */
    @NotBlank(message = "Full name cannot be blank")
    @Column(name = "full_name", nullable = false)
    private String fullName;

    /**
     * Assigned User Role string (e.g. "STUDENT", "COMPANY", "ADMIN").
     */
    @NotBlank(message = "Role cannot be blank")
    @Column(name = "role", nullable = false)
    private String role;

    /**
     * Unique Email address used for system login.
     */
    @NotBlank(message = "Email address cannot be blank")
    @Email(message = "Email address must be a valid format")
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /**
     * BCrypt Hashed Password String. Never store raw passwords.
     */
    @NotBlank(message = "Password hash cannot be blank")
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    /**
     * Soft deletion timestamp. If non-null, user is considered soft-deleted.
     */
    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

    /**
     * Timestamp recording the user's most recent successful authentication.
     */
    @Column(name = "last_login_at")
    private LocalDateTime lastLoginAt;

    /**
     * Timestamp recording when the user's password was last modified.
     */
    @Column(name = "last_password_change_at")
    private LocalDateTime lastPasswordChangeAt;

    /**
     * Counter tracking consecutive failed login attempts for account lockout policies.
     */
    @NotNull
    @Builder.Default
    @Column(name = "failed_login_attempts", nullable = false)
    private Integer failedLoginAttempts = 0;

    /**
     * Assigned Security Roles mapped via N:M join table user_roles.
     * EAGER fetch justified for Spring Security GrantedAuthority initialization.
     */
    @Builder.Default
    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinTable(
        name = "user_roles",
        joinColumns = @JoinColumn(name = "user_id", referencedColumnName = "id"),
        inverseJoinColumns = @JoinColumn(name = "role_id", referencedColumnName = "id")
    )
    private Set<Role> roles = new HashSet<>();
}
